@startuml

actor Bot
boundary SearchController
participant ClienteService
participant SearchRepositorio
participant ClienteSchema
entity SearchModel
database data

Bot -> SearchController: GET (Keyword)
activate SearchController
SearchController -> SearchModel: get_or_404()
activate SearchModel
SearchModel -> data: query (SELECT)
SearchModel <- data: Register
ClienteSchema <- SearchModel: Objeto search
deactivate SearchModel
activate ClienteSchema
SearchRepositorio <- ClienteSchema: Json search
deactivate ClienteSchema
activate SearchRepositorio
SearchController <- SearchRepositorio: SearchModel
deactivate SearchRepositorio
Bot <- SearchController: json (Response)
deactivate SearchController

@enduml